- name: Configuring the  {{ component }} repo
  ansible.builtin.copy:
    src: "{{ component }}.repo"
    dest: /etc/yum.repos.d/{{ component }}.repo

- name: Install "{{ packageName }}"
  ansible.builtin.package:
    name: "{{ packageName }}"
    state: present

- name: Start "{{ packageName }}" service
  ansible.builtin.service:
    name: mongod
    enabled: true
    state: restarted

- name: configuring the hostname
  ansible.builtin.shell: hostnamectl set-hostname {{ component }}-{{ env }}    