- name: Disable default nginx module
  ansible.builtin.shell: dnf module disable nginx -y
  
- name: enable default nginx module
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Cleanup the default nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent       

- name: Download the frontend content
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /usr/share/nginx/html
    remote_src: yes    

 

- name: configuring the hostname
  ansible.builtin.shell: hostnamectl set-hostname frontend-{{ env }}

