- name: Disable default nginx module
  ansible.builtin.dnf: 
    module_disabled: 
      - nginx
    state: absent  
  
- name: Enable nginx 1.24 module
  ansible.builtin.dnf: 
    name: nginx
    state: present
    module_enabled: 
      - nginx:1.24

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started


