- name: Configurure the roboshop repo
  become: true
  hosts: {{ component }}
  roles:
    - {{ component }}

  # ansible.builtin.template:
  #   src: roboshop.conf.j2
  #   dest: /etc/nginx/default.d/roboshop.conf